export const countries = [
    { label: "Afghanistan", value: "Afghanistan", code: "af" },
    { label: "Albania", value: "Albania", code: "al" },
    { label: "Algeria", value: "Algeria", code: "dz" },
    { label: "Andorra", value: "Andorra", code: "ad" },
    { label: "Angola", value: "Angola", code: "ao" },
    { label: "Antigua and Barbuda", value: "Antigua and Barbuda", code: "ag" },
    { label: "Argentina", value: "Argentina", code: "ar" },
    { label: "Armenia", value: "Armenia", code: "am" },
    { label: "Australia", value: "Australia", code: "au" },
    { label: "Austria", value: "Austria", code: "at" },
    { label: "Azerbaijan", value: "Azerbaijan", code: "az" },
    { label: "Bahamas", value: "Bahamas", code: "bs" },
    { label: "Bahrain", value: "Bahrain", code: "bh" },
    { label: "Bangladesh", value: "Bangladesh", code: "bd" },
    { label: "Barbados", value: "Barbados", code: "bb" },
    { label: "Belarus", value: "Belarus", code: "by" },
    { label: "Belgium", value: "Belgium", code: "be" },
    { label: "Belize", value: "Belize", code: "bz" },
    { label: "Benin", value: "Benin", code: "bj" },
    { label: "Bhutan", value: "Bhutan", code: "bt" },
    { label: "Bolivia", value: "Bolivia", code: "bo" },
    { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina", code: "ba" },
    { label: "Botswana", value: "Botswana", code: "bw" },
    { label: "Brazil", value: "Brazil", code: "br" },
    { label: "Brunei", value: "Brunei", code: "bn" },
    { label: "Bulgaria", value: "Bulgaria", code: "bg" },
    { label: "Burkina Faso", value: "Burkina Faso", code: "bf" },
    { label: "Burundi", value: "Burundi", code: "bi" },
    { label: "Cabo Verde", value: "Cabo Verde", code: "cv" },
    { label: "Cambodia", value: "Cambodia", code: "kh" },
    { label: "Cameroon", value: "Cameroon", code: "cm" },
    { label: "Canada", value: "Canada", code: "ca" },
    { label: "Central African Republic", value: "Central African Republic", code: "cf" },
    { label: "Chad", value: "Chad", code: "td" },
    { label: "Chile", value: "Chile", code: "cl" },
    { label: "China", value: "China", code: "cn" },
    { label: "Colombia", value: "Colombia", code: "co" },
    { label: "Comoros", value: "Comoros", code: "km" },
    { label: "Congo (Congo-Brazzaville)", value: "Congo (Congo-Brazzaville)", code: "cg" },
    { label: "Costa Rica", value: "Costa Rica", code: "cr" },
    { label: "Croatia", value: "Croatia", code: "hr" },
    { label: "Cuba", value: "Cuba", code: "cu" },
    { label: "Cyprus", value: "Cyprus", code: "cy" },
    { label: "Czechia (Czech Republic)", value: "Czechia (Czech Republic)", code: "cz" },
    { label: "Democratic Republic of the Congo", value: "Democratic Republic of the Congo", code: "cd" },
    { label: "Denmark", value: "Denmark", code: "dk" },
    { label: "Djibouti", value: "Djibouti", code: "dj" },
    { label: "Dominica", value: "Dominica", code: "dm" },
    { label: "Dominican Republic", value: "Dominican Republic", code: "do" },
    { label: "Ecuador", value: "Ecuador", code: "ec" },
    { label: "Egypt", value: "Egypt", code: "eg" },
    { label: "El Salvador", value: "El Salvador", code: "sv" },
    { label: "Equatorial Guinea", value: "Equatorial Guinea", code: "gq" },
    { label: "Eritrea", value: "Eritrea", code: "er" },
    { label: "Estonia", value: "Estonia", code: "ee" },
    { label: "Eswatini", value: "Eswatini", code: "sz" },
    { label: "Ethiopia", value: "Ethiopia", code: "et" },
    { label: "Fiji", value: "Fiji", code: "fj" },
    { label: "Finland", value: "Finland", code: "fi" },
    { label: "France", value: "France", code: "fr" },
    { label: "Gabon", value: "Gabon", code: "ga" },
    { label: "Gambia", value: "Gambia", code: "gm" },
    { label: "Georgia", value: "Georgia", code: "ge" },
    { label: "Germany", value: "Germany", code: "de" },
    { label: "Ghana", value: "Ghana", code: "gh" },
    { label: "Greece", value: "Greece", code: "gr" },
    { label: "Grenada", value: "Grenada", code: "gd" },
    { label: "Guatemala", value: "Guatemala", code: "gt" },
    { label: "Guinea", value: "Guinea", code: "gn" },
    { label: "Guinea-Bissau", value: "Guinea-Bissau", code: "gw" },
    { label: "Guyana", value: "Guyana", code: "gy" },
    { label: "Haiti", value: "Haiti", code: "ht" },
    { label: "Holy See", value: "Holy See", code: "va" },
    { label: "Honduras", value: "Honduras", code: "hn" },
    { label: "Hungary", value: "Hungary", code: "hu" },
    { label: "Iceland", value: "Iceland", code: "is" },
    { label: "India", value: "India", code: "in" },
    { label: "Indonesia", value: "Indonesia", code: "id" },
    { label: "Iran", value: "Iran", code: "ir" },
    { label: "Iraq", value: "Iraq", code: "iq" },
    { label: "Ireland", value: "Ireland", code: "ie" },
    { label: "Israel", value: "Israel", code: "il" },
    { label: "Italy", value: "Italy", code: "it" },
    { label: "Jamaica", value: "Jamaica", code: "jm" },
    { label: "Japan", value: "Japan", code: "jp" },
    { label: "Jordan", value: "Jordan", code: "jo" },
    { label: "Kazakhstan", value: "Kazakhstan", code: "kz" },
    { label: "Kenya", value: "Kenya", code: "ke" },
    { label: "Kiribati", value: "Kiribati", code: "ki" },
    { label: "Kuwait", value: "Kuwait", code: "kw" },
    { label: "Kyrgyzstan", value: "Kyrgyzstan", code: "kg" },
    { label: "Laos", value: "Laos", code: "la" },
    { label: "Latvia", value: "Latvia", code: "lv" },
    { label: "Lebanon", value: "Lebanon", code: "lb" },
    { label: "Lesotho", value: "Lesotho", code: "ls" },
    { label: "Liberia", value: "Liberia", code: "lr" },
    { label: "Libya", value: "Libya", code: "ly" },
    { label: "Liechtenstein", value: "Liechtenstein", code: "li" },
    { label: "Lithuania", value: "Lithuania", code: "lt" },
    { label: "Luxembourg", value: "Luxembourg", code: "lu" },
    { label: "Madagascar", value: "Madagascar", code: "mg" },
    { label: "Malawi", value: "Malawi", code: "mw" },
    { label: "Malaysia", value: "Malaysia", code: "my" },
    { label: "Maldives", value: "Maldives", code: "mv" },
    { label: "Mali", value: "Mali", code: "ml" },
    { label: "Malta", value: "Malta", code: "mt" },
    { label: "Marshall Islands", value: "Marshall Islands", code: "mh" },
    { label: "Mauritania", value: "Mauritania", code: "mr" },
    { label: "Mauritius", value: "Mauritius", code: "mu" },
    { label: "Mexico", value: "Mexico", code: "mx" },
    { label: "Micronesia", value: "Micronesia", code: "fm" },
    { label: "Moldova", value: "Moldova", code: "md" },
    { label: "Monaco", value: "Monaco", code: "mc" },
    { label: "Mongolia", value: "Mongolia", code: "mn" },
    { label: "Montenegro", value: "Montenegro", code: "me" },
    { label: "Morocco", value: "Morocco", code: "ma" },
    { label: "Mozambique", value: "Mozambique", code: "mz" },
    { label: "Myanmar (formerly Burma)", value: "Myanmar (formerly Burma)", code: "mm" },
    { label: "Namibia", value: "Namibia", code: "na" },
    { label: "Nauru", value: "Nauru", code: "nr" },
    { label: "Nepal", value: "Nepal", code: "np" },
    { label: "Netherlands", value: "Netherlands", code: "nl" },
    { label: "New Zealand", value: "New Zealand", code: "nz" },
    { label: "Nicaragua", value: "Nicaragua", code: "ni" },
    { label: "Niger", value: "Niger", code: "ne" },
    { label: "Nigeria", value: "Nigeria", code: "ng" },
    { label: "North Korea", value: "North Korea", code: "kp" },
    { label: "North Macedonia", value: "North Macedonia", code: "mk" },
    { label: "Norway", value: "Norway", code: "no" },
    { label: "Oman", value: "Oman", code: "om" },
    { label: "Pakistan", value: "Pakistan", code: "pk" },
    { label: "Palau", value: "Palau", code: "pw" },
    { label: "Palestine State", value: "Palestine State", code: "ps" },
    { label: "Panama", value: "Panama", code: "pa" },
    { label: "Papua New Guinea", value: "Papua New Guinea", code: "pg" },
    { label: "Paraguay", value: "Paraguay", code: "py" },
    { label: "Peru", value: "Peru", code: "pe" },
    { label: "Philippines", value: "Philippines", code: "ph" },
    { label: "Poland", value: "Poland", code: "pl" },
    { label: "Portugal", value: "Portugal", code: "pt" },
    { label: "Qatar", value: "Qatar", code: "qa" },
    { label: "Romania", value: "Romania", code: "ro" },
    { label: "Russia", value: "Russia", code: "ru" },
    { label: "Rwanda", value: "Rwanda", code: "rw" },
    { label: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis", code: "kn" },
    { label: "Saint Lucia", value: "Saint Lucia", code: "lc" },
    { label: "Saint Vincent and the Grenadines", value: "Saint Vincent and the Grenadines", code: "vc" },
    { label: "Samoa", value: "Samoa", code: "ws" },
    { label: "San Marino", value: "San Marino", code: "sm" },
    { label: "Sao Tome and Principe", value: "Sao Tome and Principe", code: "st" },
    { label: "Saudi Arabia", value: "Saudi Arabia", code: "sa" },
    { label: "Senegal", value: "Senegal", code: "sn" },
    { label: "Serbia", value: "Serbia", code: "rs" },
    { label: "Seychelles", value: "Seychelles", code: "sc" },
    { label: "Sierra Leone", value: "Sierra Leone", code: "sl" },
    { label: "Singapore", value: "Singapore", code: "sg" },
    { label: "Slovakia", value: "Slovakia", code: "sk" },
    { label: "Slovenia", value: "Slovenia", code: "si" },
    { label: "Solomon Islands", value: "Solomon Islands", code: "sb" },
    { label: "Somalia", value: "Somalia", code: "so" },
    { label: "South Africa", value: "South Africa", code: "za" },
    { label: "South Korea", value: "South Korea", code: "kr" },
    { label: "South Sudan", value: "South Sudan", code: "ss" },
    { label: "Spain", value: "Spain", code: "es" },
    { label: "Sri Lanka", value: "Sri Lanka", code: "lk" },
    { label: "Sudan", value: "Sudan", code: "sd" },
    { label: "Suriname", value: "Suriname", code: "sr" },
    { label: "Sweden", value: "Sweden", code: "se" },
    { label: "Switzerland", value: "Switzerland", code: "ch" },
    { label: "Syria", value: "Syria", code: "sy" },
    { label: "Tajikistan", value: "Tajikistan", code: "tj" },
    { label: "Tanzania", value: "Tanzania", code: "tz" },
    { label: "Thailand", value: "Thailand", code: "th" },
    { label: "Timor-Leste", value: "Timor-Leste", code: "tl" },
    { label: "Togo", value: "Togo", code: "tg" },
    { label: "Tonga", value: "Tonga", code: "to" },
    { label: "Trinidad and Tobago", value: "Trinidad and Tobago", code: "tt" },
    { label: "Tunisia", value: "Tunisia", code: "tn" },
    { label: "Turkey", value: "Turkey", code: "tr" },
    { label: "Turkmenistan", value: "Turkmenistan", code: "tm" },
    { label: "Tuvalu", value: "Tuvalu", code: "tv" },
    { label: "Uganda", value: "Uganda", code: "ug" },
    { label: "Ukraine", value: "Ukraine", code: "ua" },
    { label: "United Kingdom", value: "United Kingdom", code: "gb" },
    { label: "United States of America", value: "United States of America", code: "us" },
    { label: "Uruguay", value: "Uruguay", code: "uy" },
    { label: "Uzbekistan", value: "Uzbekistan", code: "uz" },
    { label: "Vanuatu", value: "Vanuatu", code: "vu" },
    { label: "Venezuela", value: "Venezuela", code: "ve" },
    { label: "Vietnam", value: "Vietnam", code: "vn" },
    { label: "Yemen", value: "Yemen", code: "ye" },
    { label: "Zambia", value: "Zambia", code: "zm" },
    { label: "Zimbabwe", value: "Zimbabwe", code: "zw" }
];
